AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'db/**/*'

# Accept single-line methods with no body
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Top-level documentation of clases and modules are needless
Documentation:
  Enabled: false

# Allow to chain of block after another block that spans multiple lines
MultilineBlockChain:
  Enabled: false

# Allow `->` literal for multi line blocks
Lambda:
  Enabled: false

# Both nested and compact are okay
ClassAndModuleChildren:
  Enabled: false

# Specifying param names is unnecessary
Style/SingleLineBlockParams:
  Enabled: false

# Prefer Kernel#sprintf
FormatString:
  EnforcedStyle: sprintf

# Maximum line length
LineLength:
  Max: 100

# Whatever we should use "postfix if/unless"
IfUnlessModifier:
  MaxLineLength: 100

# Maximum method length
MethodLength:
  Max: 20

# Prefer double_quotes strings unless your string literal contains escape chars
StringLiterals:
  EnforcedStyle: double_quotes
